### ISSUE TITLE
installing the package Extra-Streamlit-Components error 

### ISSUE THREAD

**Issue by mohmadkilane** [Mohamed-512/Extra-Streamlit-Components#26]
Hi @Mohamed-512 
i got this error when trying to pip install your package into my local docker , 

Error log : 
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 413, in run
    pycompile=options.compile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 81, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 810, in install
    requested=self.user_supplied,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/wheel.py", line 737, in install_wheel
    requested=requested,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
    [file.save](http://file.save/)()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/wheel.py", line 383, in save
    if os.path.exists(self.dest_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f4f9' in position 63: ordinal not in range(128)
subprocess exited with status 2
subprocess exited with status 2
error building at STEP "RUN pip3 install extra-streamlit-components==0.1.53": exit status 2

docker file : 

FROM ubuntu:bionic
EXPOSE XXXX
ENV http_proxy=XXXXXXXX
ENV https_proxy=XXXXXXXXX
RUN apt-get update
RUN apt-get -y install python3.8 python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install -U setuptools
RUN pip3 install pymongo==3.11.2
RUN pip3 install matplotlib==3.3.3
RUN pip3 install psycopg2-binary==2.8.6
RUN pip3 install pyaml==20.4.0
RUN pip3 install markdown==3.3.3
RUN pip3 install numpy==1.19.5
RUN pip3 install plotly_express==0.4.1
RUN pip3 install mapboxgl==0.10.2
RUN pip3 install pydeck==0.5.0
RUN pip3 install bokeh==2.2.3
RUN pip3 install plotly==4.10.0
RUN pip3 install colorama==0.4.4
RUN pip3 install coloredlogs==15.0
RUN pip3 install python-json-logger==2.0.1
RUN pip3 install jmespath==0.9.4
**RUN pip3 install extra-streamlit-components==0.1.53**
RUN pip3 install dataclasses==0.8
RUN pip3 install streamlit==1.5.1
RUN pip3 install pathlib2==2.3.6
RUN pip3 install py4j pyarrow==3.0.0
CMD streamlit run $START_CMD --server.maxUploadSize=1028

**Comment by Mohamed-512** [comment]
Hope you have fixed it by now but I think you need to install `streamlit` first.
